using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Utilities.Utility.#Deserialize`1(System.String)", MessageId = "json")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Controller.NDTVController", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Entities", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Controller", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Processor", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Processor.NDTVProcessor", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Connector", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.SlateApp.Converter", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Interfaces", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.Utilities", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.SlateApp.View", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.SlateApp.ViewModel", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.SlateApp", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Pages.#SensexScoreCardSmall", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Pages.#SensexScoreCardBig", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#TeamAFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#TeamBFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.CricketInnings.#BowlingTeamFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.CricketInnings.#BattingTeamFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.InningsSummary.#TeamFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.InningsSummary.#BowlingTeamFlag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "NDTV.Utilities.HttpHelper")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "NDTV.SlateApp.View.CricketCalendarControl.#ShowScoreCard(System.Object,System.Windows.RoutedEventArgs)")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.CricketInningsEquation.#TotalOvers", MessageId = "Overs")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.InningsExtra.#Wides", MessageId = "Wides")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.CricketBowler.#Overs", MessageId = "Overs")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.CricketBowler.#Wides", MessageId = "Wides")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.CricketBowler.#MaidenOvers", MessageId = "Overs")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#MatchTimeIST", MessageId = "IST")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#MatchDateIST", MessageId = "IST")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.MiniScoreCard.#ShowFullScoreFromMiniScoreCard")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.MiniScoreCard.#ShowFullCommentaryFromMiniScoreCard")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.CricketCalendarControl.#ShowScorecardEvent")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.CricketCommentary.#CloseFullCommentaryButtonClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.CricketCommentary.#ShowFullScoreCardFromCommentaryButtonClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScoreCard.#FullCommentaryFromFullScoreCardClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScoreCard.#FullScoreCardCloseClick")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#TeamAId", MessageId = "AId")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CricketFixtures.#TeamBId", MessageId = "BId")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp", MessageId = "InterOp")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp", MessageId = "Op")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#NotificationReceived")]
[module: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#NotificationReceived")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScorecard.#FullCommentaryFromFullScoreCardClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScorecard.#FullScoreCardCloseClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.CricketCommentary.#ShowFullScorecardFromCommentaryButtonClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.MiniScorecard.#ShowFullCommentaryFromMiniScoreCard")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.MiniScorecard.#ShowFullScoreFromMiniScorecard")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.CricketBatsman.#BatsmenList")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.CricketInnings.#BowlerList")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.MiniScorecardItem.#CurrentlyPlayingBatsmen")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.MiniScorecardItem.#CurrentlyBowlingBowler")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.CricketBowler.#BowlerList")]
[module: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "NDTV.SlateApp.View.FullScorecard.#FullScoreCardCloseClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.MiniScorecard.#ShowFullCommentaryFromMiniScorecard")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScorecard.#FullCommentaryFromFullScorecardClick")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScorecard.#FullScorecardCloseClick")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+TopStories+Categories")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#ScoreCards")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#PhotoAlbums")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ArticlePageViewModel.#TopStoriesLatest")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.Category.#CategoryItemList")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#IsLandingPageLoaded", MessageId = "IsLanding")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CategoryItem.#ThumbNailImageLink", MessageId = "ThumbNail")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Entities.LatestNewsFeedResponse", MessageId = "NewsFeed")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Entities.LatestNewsFeedRequest", MessageId = "NewsFeed")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#TopStoriesContainer4")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#TopStoriesContainer1")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#TopStoriesContainer2")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#StockTickerDetails")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#PhotoAlbums")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.LandingPageViewModel.#VideoItems")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.ArticlePageViewModel.#TopStoriesLatest")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.SlateApp.ViewModel.ArticlePageViewModel.#TopStoriesContainer1")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope="member", Target="NDTV.Entities.TopStory.#TopStoryCollection")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#ScoreCards")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#PhotoAlbums")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ArticlePageViewModel.#TopStoriesLatest")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.Category.#CategoryItemList")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Utilities.Utility.#GetDefaultNdtvImageSource()", MessageId = "Ndtv")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#ResetPreloaderFlags()", MessageId = "Preloader")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.StockViewModel.#StockTickerDetails")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.Framework.CustomEventArgs.SearchCompletedEventArgs.#SearchResults")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.Framework.CustomEventArgs.StocksLoadedEventArgs.#.ctor(System.Collections.Generic.List`1<NDTV.Entities.StockItemDetails>)")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.SlateApp.View.SensexScorecard", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.CricketShortScorecardResponse.#Scorecards")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.CompanySpecificStockData.#ISIN", MessageId = "ISIN")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.StockItem.#Items")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.StockItem.#Items")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignature(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "10#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignature(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "11#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignature(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "13#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignature(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "12#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignatureBase(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "13#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.OAuthHelper.#GenerateSignatureBase(System.Uri,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String&,System.String&)", MessageId = "12#")]
[module: SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", Scope = "member", Target = "NDTV.Utilities.Utility.#XElementTryParse(System.String,System.Xml.Linq.XElement&)", MessageId = "1#")]
[module: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "NDTV.Connector.HttpConnector.#ServiceRequestCallback(System.IAsyncResult)")]
[module: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "NDTV.Connector.HttpConnector.#Submit(System.String,System.String,System.String,System.String,System.String,System.String,NDTV.Entities.HttpAuthentication,System.Boolean)")]
[module: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "NDTV.Connector.HttpConnector.#ServiceResponseCallback(System.IAsyncResult)")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ViewModelBase.#showOfflineErrorMessage")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#requestUserName")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#requestPassword")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#requestHeader")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#requestLink")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#rawRequest")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#enableCache")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#response")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Request.#authentication")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Response.#responseException")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "NDTV.Entities.Response.#responseMessage")]
[module: SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "NDTV.Entities.Request")]
[module: SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "NDTV.Entities.Response")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+LiveTVPlayMode")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+VideoPlayerNotificationConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+HttpMethodNames")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+TopStories")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+ReportErrorKeys")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+LoggingConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+LinkNames")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+TwitterConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+FacebookConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+Constant")]
[module: SuppressMessage("Microsoft.Naming", "CA1708:IdentifiersShouldDifferByMoreThanCase", Scope = "type", Target = "NDTV.Entities.Request")]
[module: SuppressMessage("Microsoft.Naming", "CA1708:IdentifiersShouldDifferByMoreThanCase", Scope = "type", Target = "NDTV.Entities.Response")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Utilities.Utility.#FetchDefaultNdtvImageSource()", MessageId = "Ndtv")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#NDTVWeatherPageLink", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVGoodTimesSchedule", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVProfitSchedule", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTV24x7VideoLink", MessageId = "x")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTV24x7VideoLink", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVIndiaSchedule", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVHinduSchedule", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVIndiaVideoLink", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTV24x7Id", MessageId = "x")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTV24x7Schedule", MessageId = "x")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTV24x7Schedule", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVProfitVideoLink", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#LiveTVNDTVGoodTimesVideoLink", MessageId = "TVNDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.TopStoryItem.#LinkForRSS", MessageId = "RSS")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselWindow.#FullScreenGalleryControlCloseEvent()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselWindow.#AlbumClickEvent(System.Object,NDTV.SlateApp.Framework.CustomEventArgs.CarouselAlbumArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselWindow.#CarouselCloseEvent()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselWindow.#ImageGalleryControlFullScreenEvent(System.Object,NDTV.SlateApp.Framework.CustomEventArgs.ImageGalleryArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselWindow.#ImageControlCloseEvent()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.FullScreenImageGalleryControl.#GoBackMainGallerySmallEvent(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.FullScreenImageGalleryControl.#TapDownOnPanningItem(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.Article.#ArticleClick(System.Object,System.EventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumGalleryWindow.#ImageGalleryControlFullScreenEvent(System.Object,NDTV.SlateApp.Framework.CustomEventArgs.ImageGalleryArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumGalleryWindow.#FullScreenGalleryControlCloseEvent()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumGalleryWindow.#ImageControlCloseEvent()")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.VideoPageViewModel.#VideoList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.VideoPlayerViewModel.#LatestVideos")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ChannelScheduleViewModel.#VideoList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.ViewModel.RelatedItemsViewModel.#VideoList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.Framework.Model.Entities.Comments.#CommentList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.Framework.CustomEventArgs.CarouselAlbumArgs.#RelatedAlbumLists")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.Framework.CustomEventArgs.ImageGalleryArgs.#ImageList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Controller.ApplicationData.#TotalImagesOfSelectedAlbum")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Controller.ApplicationData.#StockMarketList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Controller.ApplicationData.#ImagesCategoryList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Controller.ApplicationData.#RelatedVideoList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.SlateApp.View.ImageGalleryControl.#RelatedAlbumList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.LatestNews.#latestNewsCollection")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.RelatedVideosResponse.#RelatedVideoList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.CricketInnings.#BowlerList")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.MiniScorecardItem.#CurrentlyPlayingBatsmen")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.MiniScorecardItem.#CurrentlyBowlingBowler")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "NDTV.Entities.ProfitFlashNewsItem.#ItemDetails")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+Constant.#Vs", MessageId = "Vs")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+Constant.#Sensex", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+Constant.#PngExtension", MessageId = "Png")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "type", Target = "NDTV.SlateApp.View.SocialLogin", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "type", Target = "NDTV.Entities.LoginMode", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.UserData.#LoginMode", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.FacebookAccount.#LoginControl", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.Entities.TwitterAccount.#LoginControl", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+CommentConstants")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Controller.ApplicationData.#FacebookAccount", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.LoginMode.#Facebook", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.SocialInteractionType.#Facebook", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.FacebookUserDataResponse.#FacebookUser", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookAccount", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.FacebookAccount.#FacebookUser", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookUser", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#SensexStocksLink", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookShareResponse", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookShareRequest", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookUserDataRequest", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.Constants+FacebookConstants", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.Framework.Model.Entities.Comments.#CommentList")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Controller.ApplicationData.#ImagesCategoryList")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.ImageItemResponse.#ImageItemCollection")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.ProfitFlashNewsItem.#ItemDetails")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.ImageCategoriesResponse.#ImageCategoryCollection")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.Entities.ImageAlbumResponse.#ImageAlbumCollection")]
[module: SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", Scope = "member", Target = "NDTV.SlateApp.Converter.ImageForwardButtonEnableConverter.#Convert(System.Object[],System.Type,System.Object,System.Globalization.CultureInfo)", MessageId = "System.Int32.TryParse(System.String,System.Int32@)")]
[module: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ViewModelBase.#OnCollectionChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[module: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LandingPageViewModel.#Scorecards")]
[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "NDTV.SlateApp.ViewModel.ArticlePageViewModel.#isLoaded")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "type", Target = "NDTV.SlateApp.ViewModel.LoginOptionsViewModel", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LoginOptionsViewModel.#GetInteractionType(System.Object)", MessageId = "System.Enum.TryParse<NDTV.Entities.LoginMode>(System.String,NDTV.Entities.LoginMode@)")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LoginOptionsViewModel.#Login", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "namespace", Target = "NDTV.SlateApp.Framework.Utilities", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#InjectJavaScriptFunction(System.Windows.Controls.WebBrowser,System.String,System.String)")]
[module: SuppressMessage("Microsoft.Interoperability", "CA1407:AvoidStaticMembersInComVisibleTypes", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#HideScriptErrors(System.Windows.Controls.WebBrowser,System.Boolean)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1304:SpecifyCultureInfo", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#HideScriptErrors(System.Windows.Controls.WebBrowser,System.Boolean)", MessageId = "System.Type.InvokeMember(System.String,System.Reflection.BindingFlags,System.Reflection.Binder,System.Object,System.Object[])")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.SlateApp.Framework.Utilities.JavaScriptInterOp.#HideScriptErrors(System.Windows.Controls.WebBrowser,System.Boolean)", MessageId = "Hide")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+RegisterUserConstants")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+Constant.#Username", MessageId = "Username")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+LinkedInConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+GoogleConstants")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookUserDataResponse", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookAccessTokenResponse", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "NDTV.Entities.YahooTokenResponse.#.ctor(System.String)", MessageId = "string")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "NDTV.Entities.YahooUserDataResponse.#.ctor(System.String)", MessageId = "string")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "NDTV.Entities.GoogleUserDetailsResponse.#.ctor(System.String)", MessageId = "string")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Constants+LinkNames.#ImageResizerLink", MessageId = "Resizer")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "NDTV.Entities.FacebookAccessTokenRequest", MessageId = "Facebook")]
[module: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "NDTV.Entities.Constants+YahooConstants")]
[module: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "NDTV.Utilities.Utility.#Deserialize`1(System.IO.Stream)")]
[module: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "NDTV.Utilities.Utility.#Deserialize`1(System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "NDTV.Utilities.Utility.#DeserializeFromXml`1(System.String)")]
[module: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "NDTV.Utilities.DataFragmentation`1.#Fragment(System.Int32,System.Object,System.Object,NDTV.Utilities.DataFragmentation`1<!0>+FragmentedDataflow,System.Int32)")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.SlateApp.ViewModel.CommentsViewModel.#LoginClick", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.SlateApp.ViewModel.CommentsViewModel.#LoginVisible", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1708:IdentifiersShouldDifferByMoreThanCase", Scope = "type", Target = "NDTV.SlateApp.SlateWindow")]
[module: SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "NDTV.SlateApp.SlateWindow.#OpenPopupWindow(NDTV.SlateApp.SlateWindow,NDTV.SlateApp.SlateWindow,System.Windows.Shapes.Rectangle,System.Action`1<System.Boolean>)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "NDTV.SlateApp.SlateWindow.#OpenPopupWindow(NDTV.SlateApp.SlateWindow,NDTV.SlateApp.SlateWindow,System.Windows.Shapes.Rectangle,System.Action`1<System.Boolean>)")]
[module: SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "NDTV.Connector.HttpConnector.#RaiseException(System.Exception)")]
[module: SuppressMessage("Microsoft.Usage", "CA2234:PassSystemUriObjectsInsteadOfStrings", Scope = "member", Target = "NDTV.Connector.HttpConnector.#Submit(System.String,System.String,System.String,System.String,System.String,System.String,NDTV.Entities.HttpAuthentication,System.Boolean)")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "NDTV.Controller.NDTVController.#ProcessRequest(NDTV.Entities.Request,NDTV.Interfaces.ProcessResponse,System.Action`1<System.Exception>)")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Entities.BitLyData", MessageId = "Ly")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "NDTV.Entities.NDTVSlateUser", MessageId = "NDTV")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Utilities.Utility.#FetchDefaultNdtvImageSource(System.String)", MessageId = "Ndtv")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Pages.#SensexScorecardSmall", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "NDTV.Entities.Pages.#SensexScorecardBig", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "NDTV.SlateApp.SlateWindow.#InitializeCurrentOrientation()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "NDTV.SlateApp.SlateWindow.#OpenPopUpWindow(NDTV.SlateApp.SlateWindow,NDTV.SlateApp.SlateWindow,System.Windows.Shapes.Rectangle)")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "NDTV.SlateApp.MainWindow.#.ctor()")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "NDTV.SlateApp.View.VideoPlayer.#.ctor(NDTV.Entities.VideoItem)")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "NDTV.SlateApp.View.Article.#.ctor(NDTV.Entities.TopStoryItem,NDTV.Entities.TopStory)")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.ImageGalleryControl.#RaiseWindowCloseEventHandler")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.FullScreenImageGalleryControl.#RaiseCloseUserControlEvent")]
[module: SuppressMessage("Microsoft.Design", "CA1009:DeclareEventHandlersCorrectly", Scope = "member", Target = "NDTV.SlateApp.View.ImageAlbumCarouselControl.#RaiseImageAlbumCarouselCloseEvent")]
[module: SuppressMessage("Microsoft.Naming", "CA1708:IdentifiersShouldDifferByMoreThanCase", Scope = "type", Target = "NDTV.Entities.LinkShortenResponse")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NDTV.SlateApp.Properties.Resources.resources", MessageId = "ndtv")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NDTV.SlateApp.Properties.Resources.resources", MessageId = "Argh")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NDTV.SlateApp.Properties.Resources.resources", MessageId = "pics")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NDTV.SlateApp.Properties.Resources.resources", MessageId = "Sensex")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "type", Target = "NDTV.SlateApp.View.LoginOptions", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "NDTV.SlateApp.ViewModel.LoginOptionsViewModel.#CancelLogin", MessageId = "Login")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.LoginOptions.#CloseButtonClicked(System.Object,System.Windows.RoutedEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.CommentsControl.#CloseButtonClicked(System.Object,System.Windows.RoutedEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.MailShare.#CloseButtonClicked(System.Object,System.Windows.RoutedEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.SocialLogin.#CloseButtonClick(System.Object,System.Windows.RoutedEventArgs)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NDTV.SlateApp.View.SocialShareDialog.#CloseButtonClicked(System.Object,System.Windows.RoutedEventArgs)")]



