//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDTV.SlateApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDTV.SlateApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Comments ({0}).
        /// </summary>
        public static string AllComments {
            get {
                return ResourceManager.GetString("AllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to share this error with us anonymously?.
        /// </summary>
        public static string AnonymousFeedbackMessage {
            get {
                return ResourceManager.GetString("AnonymousFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, another instance of the application is running..
        /// </summary>
        public static string AnotherInstanceofApplicationRunning {
            get {
                return ResourceManager.GetString("AnotherInstanceofApplicationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, we were unable to load the application. Please check your internet connection and try again..
        /// </summary>
        public static string ApplicationLoadFailureMessage {
            get {
                return ResourceManager.GetString("ApplicationLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSE.
        /// </summary>
        public static string BSE {
            get {
                return ResourceManager.GetString("BSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°C.
        /// </summary>
        public static string CelsiusSuffix {
            get {
                return ResourceManager.GetString("CelsiusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, we are unable to post your comment. Please check your internet connection and try again..
        /// </summary>
        public static string CommentPostError {
            get {
                return ResourceManager.GetString("CommentPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string CommentsButtonContent {
            get {
                return ResourceManager.GetString("CommentsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1}.
        /// </summary>
        public static string CommentsIdentifier {
            get {
                return ResourceManager.GetString("CommentsIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong. Try again later..
        /// </summary>
        public static string CommentsPostError {
            get {
                return ResourceManager.GetString("CommentsPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already posted this comment..
        /// </summary>
        public static string CommentsPostRepeatError {
            get {
                return ResourceManager.GetString("CommentsPostRepeatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as {0} on {1}.
        /// </summary>
        public static string CommentsSubTitle {
            get {
                return ResourceManager.GetString("CommentsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, we were unable to get the latest content. Please check your internet connection and try again..
        /// </summary>
        public static string ContentLoadFailureMessage {
            get {
                return ResourceManager.GetString("ContentLoadFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argh, we were unable to share this with your friends on {0}. Please check your internet connection and try again..
        /// </summary>
        public static string ContentShareFailureMessage {
            get {
                return ResourceManager.GetString("ContentShareFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out {0} on NDTV Slate..
        /// </summary>
        public static string ContentShareMessage {
            get {
                return ResourceManager.GetString("ContentShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sports.ndtv.com/cricket/fixtures.
        /// </summary>
        public static string CricketFixturesLink {
            get {
                return ResourceManager.GetString("CricketFixturesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} ({2} OVERS).
        /// </summary>
        public static string CricketScoreSummary {
            get {
                return ResourceManager.GetString("CricketScoreSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sports.ndtv.com/cricket/scoreboard?filename={0}.
        /// </summary>
        public static string CricketShareLink {
            get {
                return ResourceManager.GetString("CricketShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        public static string CurrentPhotoAgainstTotalPhotosIncompleteText {
            get {
                return ResourceManager.GetString("CurrentPhotoAgainstTotalPhotosIncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        public static string DefaultWeatherCity {
            get {
                return ResourceManager.GetString("DefaultWeatherCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mention a valid email format..
        /// </summary>
        public static string EmailFormatErrorMessage {
            get {
                return ResourceManager.GetString("EmailFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry couldn&apos;t log into {0}. Please try later..
        /// </summary>
        public static string ErrorLogIn {
            get {
                return ResourceManager.GetString("ErrorLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry couldn&apos;t share the {0}..
        /// </summary>
        public static string ErrorShare {
            get {
                return ResourceManager.GetString("ErrorShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am reading &apos;{0}&apos; on NDTV Slate. Check it out!.
        /// </summary>
        public static string FacebookArticleShareMessage {
            get {
                return ResourceManager.GetString("FacebookArticleShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string FacebookButtonContent {
            get {
                return ResourceManager.GetString("FacebookButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the live score of {0} on NDTV Slate. Do take a look!.
        /// </summary>
        public static string FacebookCricketLiveMatchShareMessage {
            get {
                return ResourceManager.GetString("FacebookCricketLiveMatchShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the score of {0} on NDTV Slate. Do take a look!.
        /// </summary>
        public static string FacebookCricketRecentMatchShareMessage {
            get {
                return ResourceManager.GetString("FacebookCricketRecentMatchShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am viewing &apos;{0}&apos; pics on NDTV Slate. Check it out!.
        /// </summary>
        public static string FacebookPhotoSetShareMessage {
            get {
                return ResourceManager.GetString("FacebookPhotoSetShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of recent cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string FacebookRecentMatchesShare {
            get {
                return ResourceManager.GetString("FacebookRecentMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of upcoming cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string FacebookUpcomingMatchesShare {
            get {
                return ResourceManager.GetString("FacebookUpcomingMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am watching &apos;{0}&apos; on NDTV Slate. Check it out!.
        /// </summary>
        public static string FacebookVideoShareMessage {
            get {
                return ResourceManager.GetString("FacebookVideoShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the weather update on NDTV Slate. Do take a look!.
        /// </summary>
        public static string FacebookWeather {
            get {
                return ResourceManager.GetString("FacebookWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to comment..
        /// </summary>
        public static string FirstToComment {
            get {
                return ResourceManager.GetString("FirstToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainers.
        /// </summary>
        public static string GainersText {
            get {
                return ResourceManager.GetString("GainersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong. Please check your internet connection and try again..
        /// </summary>
        public static string GeneralFailureMessage {
            get {
                return ResourceManager.GetString("GeneralFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, we are unable to retrieve comments. Please check your internet connection and try again..
        /// </summary>
        public static string GetCommentsError {
            get {
                return ResourceManager.GetString("GetCommentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indian.
        /// </summary>
        public static string Indian {
            get {
                return ResourceManager.GetString("Indian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IST at .
        /// </summary>
        public static string ISTText {
            get {
                return ResourceManager.GetString("ISTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m reading &apos;{0}&apos; on NDTV Slate. Check it out!.
        /// </summary>
        public static string LinkedInArticleShareMessage {
            get {
                return ResourceManager.GetString("LinkedInArticleShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string LinkedInButtonContent {
            get {
                return ResourceManager.GetString("LinkedInButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m checking out the live score of {0} on NDTV Slate. Do take a look!.
        /// </summary>
        public static string LinkedInCricketLiveMatchShareMessage {
            get {
                return ResourceManager.GetString("LinkedInCricketLiveMatchShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m checking out the score of {0} on NDTV Slate. Do take a look!.
        /// </summary>
        public static string LinkedInCricketRecentMatchShareMessage {
            get {
                return ResourceManager.GetString("LinkedInCricketRecentMatchShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m viewing &apos;{0}&apos; pics on NDTV Slate. Check it out!.
        /// </summary>
        public static string LinkedInPhotoSetShareMessage {
            get {
                return ResourceManager.GetString("LinkedInPhotoSetShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m checking out the details of recent cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string LinkedInRecentMatchesShare {
            get {
                return ResourceManager.GetString("LinkedInRecentMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m checking out the details of upcoming cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string LinkedInUpcomingMatchesShare {
            get {
                return ResourceManager.GetString("LinkedInUpcomingMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m watching &apos;{0}&apos; on NDTV Slate. Check it out!.
        /// </summary>
        public static string LinkedInVideoShareMessage {
            get {
                return ResourceManager.GetString("LinkedInVideoShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the weather update on NDTV Slate. Do take a look!.
        /// </summary>
        public static string LinkedInWeatherShareMessage {
            get {
                return ResourceManager.GetString("LinkedInWeatherShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE:.
        /// </summary>
        public static string LiveText {
            get {
                return ResourceManager.GetString("LiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losers.
        /// </summary>
        public static string LosersText {
            get {
                return ResourceManager.GetString("LosersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am reading &apos;{0}&apos; on NDTV Slate. Do check it out! 
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyArticle {
            get {
                return ResourceManager.GetString("MailBodyArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am reading the commentary of {0} on NDTV Slate. Do take a look!
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketLiveCommentary {
            get {
                return ResourceManager.GetString("MailBodyCricketLiveCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the live score of {0} on NDTV Slate. Do take a look!
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketLiveScorecard {
            get {
                return ResourceManager.GetString("MailBodyCricketLiveScorecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am reading the commentary of {0} on NDTV Slate. Do take a look!
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketRecentCommentary {
            get {
                return ResourceManager.GetString("MailBodyCricketRecentCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of recent cricket matches on NDTV Slate. Do take a look!
        ///
        ///{0}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketRecentMatchList {
            get {
                return ResourceManager.GetString("MailBodyCricketRecentMatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the score of {0} on NDTV Slate. Do take a look!
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketRecentScorecard {
            get {
                return ResourceManager.GetString("MailBodyCricketRecentScorecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of upcoming cricket matches on NDTV Slate. Do take a look!
        ///
        ///{0}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyCricketUpcomingMatchList {
            get {
                return ResourceManager.GetString("MailBodyCricketUpcomingMatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700.
        /// </summary>
        public static string MailBodyLimit {
            get {
                return ResourceManager.GetString("MailBodyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am viewing &apos;{0}&apos; on NDTV Slate. Do check it out! 
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyPhotoSet {
            get {
                return ResourceManager.GetString("MailBodyPhotoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am watching &apos;{0}&apos; on NDTV Slate. Do check it out! 
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyVideo {
            get {
                return ResourceManager.GetString("MailBodyVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the weather update on NDTV Slate. Do take a look!
        ///
        ///{0}
        ///
        ///Thanks,.
        /// </summary>
        public static string MailBodyWeather {
            get {
                return ResourceManager.GetString("MailBodyWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MailButtonContent {
            get {
                return ResourceManager.GetString("MailButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string MailCaptionLimit {
            get {
                return ResourceManager.GetString("MailCaptionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string MailDescriptionLimit {
            get {
                return ResourceManager.GetString("MailDescriptionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; on NDTV Slate.
        /// </summary>
        public static string MailHeaderArticle {
            get {
                return ResourceManager.GetString("MailHeaderArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; on NDTV Slate.
        /// </summary>
        public static string MailHeaderCricketLiveCommentary {
            get {
                return ResourceManager.GetString("MailHeaderCricketLiveCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; on NDTV Slate..
        /// </summary>
        public static string MailHeaderCricketLiveScorecard {
            get {
                return ResourceManager.GetString("MailHeaderCricketLiveScorecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; on NDTV Slate.
        /// </summary>
        public static string MailHeaderCricketRecentCommentary {
            get {
                return ResourceManager.GetString("MailHeaderCricketRecentCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out recent cricket matches on NDTV Slate.
        /// </summary>
        public static string MailHeaderCricketRecentMatchList {
            get {
                return ResourceManager.GetString("MailHeaderCricketRecentMatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out recent cricket matches on NDTV Slate.
        /// </summary>
        public static string MailHeaderCricketRecentScorecard {
            get {
                return ResourceManager.GetString("MailHeaderCricketRecentScorecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out upcoming cricket matches on NDTV Slate.
        /// </summary>
        public static string MailHeaderCricketUpcomingMatchList {
            get {
                return ResourceManager.GetString("MailHeaderCricketUpcomingMatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; pics on NDTV Slate.
        /// </summary>
        public static string MailHeaderPhotoSet {
            get {
                return ResourceManager.GetString("MailHeaderPhotoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string MailHeaderTitleLimit {
            get {
                return ResourceManager.GetString("MailHeaderTitleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out &apos;{0}&apos; video on NDTV Slate.
        /// </summary>
        public static string MailHeaderVideo {
            get {
                return ResourceManager.GetString("MailHeaderVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the latest weather updates on NDTV Slate.
        /// </summary>
        public static string MailHeaderWeather {
            get {
                return ResourceManager.GetString("MailHeaderWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string MailReceiverNameLimit {
            get {
                return ResourceManager.GetString("MailReceiverNameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string MailSenderNameLimit {
            get {
                return ResourceManager.GetString("MailSenderNameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, we are unable to share content via mail. Please check your internet connection and try again..
        /// </summary>
        public static string MailShareError {
            get {
                return ResourceManager.GetString("MailShareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageHeader {
            get {
                return ResourceManager.GetString("MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Saved..
        /// </summary>
        public static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active.
        /// </summary>
        public static string MostActiveText {
            get {
                return ResourceManager.GetString("MostActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nifty Stocks.
        /// </summary>
        public static string NiftyText {
            get {
                return ResourceManager.GetString("NiftyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upcoming/live matches..
        /// </summary>
        public static string NoUpcomingMatchText {
            get {
                return ResourceManager.GetString("NoUpcomingMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSE.
        /// </summary>
        public static string NSE {
            get {
                return ResourceManager.GetString("NSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonContent {
            get {
                return ResourceManager.GetString("OkButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostButtonContent {
            get {
                return ResourceManager.GetString("PostButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to post a comment..
        /// </summary>
        public static string PostCommentHeader {
            get {
                return ResourceManager.GetString("PostCommentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s Email ID.
        /// </summary>
        public static string ReceiversEmail {
            get {
                return ResourceManager.GetString("ReceiversEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s Name.
        /// </summary>
        public static string ReceiversName {
            get {
                return ResourceManager.GetString("ReceiversName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send anonymous feedback.
        /// </summary>
        public static string ReportErrorFailure {
            get {
                return ResourceManager.GetString("ReportErrorFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reported in NDTV slate application.
        /// </summary>
        public static string ReportErrorSubject {
            get {
                return ResourceManager.GetString("ReportErrorSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous feedback sent successfully.
        /// </summary>
        public static string ReportErrorSuccess {
            get {
                return ResourceManager.GetString("ReportErrorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email ID.
        /// </summary>
        public static string SendersEmail {
            get {
                return ResourceManager.GetString("SendersEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string SendersName {
            get {
                return ResourceManager.GetString("SendersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensex Stocks.
        /// </summary>
        public static string SensexText {
            get {
                return ResourceManager.GetString("SensexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this {0}.
        /// </summary>
        public static string SocialShareTitle {
            get {
                return ResourceManager.GetString("SocialShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data for the selected category!!.
        /// </summary>
        public static string StockCategoriesError {
            get {
                return ResourceManager.GetString("StockCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve data for the selected company!!.
        /// </summary>
        public static string StockItemError {
            get {
                return ResourceManager.GetString("StockItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for posting a comment. Your comment will appear post moderation..
        /// </summary>
        public static string SuccessfulPostMessage {
            get {
                return ResourceManager.GetString("SuccessfulPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet.
        /// </summary>
        public static string TwitterButtonContent {
            get {
                return ResourceManager.GetString("TwitterButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of recent cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string TwitterRecentMatchesShare {
            get {
                return ResourceManager.GetString("TwitterRecentMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 114.
        /// </summary>
        public static string TwitterTitleLimit {
            get {
                return ResourceManager.GetString("TwitterTitleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the details of upcoming cricket matches on NDTV Slate. Do take a look!.
        /// </summary>
        public static string TwitterUpcomingMatchesShare {
            get {
                return ResourceManager.GetString("TwitterUpcomingMatchesShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am checking out the weather update on NDTV Slate. Do take a look!.
        /// </summary>
        public static string TwitterWeatherTitle {
            get {
                return ResourceManager.GetString("TwitterWeatherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPCOMING:.
        /// </summary>
        public static string UpcomingText {
            get {
                return ResourceManager.GetString("UpcomingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52-Week High.
        /// </summary>
        public static string YearHighText {
            get {
                return ResourceManager.GetString("YearHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52-Week Low.
        /// </summary>
        public static string YearLowText {
            get {
                return ResourceManager.GetString("YearLowText", resourceCulture);
            }
        }
    }
}
